version: "3.8"

services:
  map-sync:
    image: ghcr.io/civplatform/map-sync
    build: .
    stdin_open: true
    tty: true
    init: true
    user: "adsombrero"
    ports:
      - 12312:12312
    volumes:
      - ./data:/data
